version: '3.5'

services:
  db: 
    image: bitnami/mongodb:6.0
    environment:
      - MONGODB_ROOT_PASSWORD=secret
      - MONGODB_USERNAME=app
      - MONGODB_PASSWORD=secret
      - MONGODB_DATABASE=app
    ports:
      - 27017:27017
  cron:
    build: ./services/cron
    env_file:
      - ./services/cron/.env
    depends_on:
      - db