import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Acá va: 
            <code className={styles.code}> Dolar</code>
          </p>
          <p>
            También va: 
            <code className={styles.code}> UF</code>
          </p>
          <p>
            Y también:
            <code className={styles.code}> Tiempo hoy</code>
          </p>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/god.png"
            alt="Next.js Logo"
            width={300}
            height={300}
            priority
          />
          <p> Perdón rolito no soy bueno en esto :( </p>
        </div>

        <div className={styles.description}>
          <p>
            Acá va el crucigrama:
            <code className={styles.code}> Crucigrama</code>
          </p>

          <p>
            Aquí un buenos día profe para que se vea bonito
          </p>
        </div>
      </main>
    </>
  )
}
