# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/alta.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/alta.proto\"%\n\x15GetTemperatureRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"-\n\x16GetTemperatureResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x05\"\x1c\n\x0cGetUFRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x1b\n\rGetUFResponse\x12\n\n\x02uf\x18\x01 \x01(\x05\"\x1f\n\x0fGetDolarRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"!\n\x10GetDolarResponse\x12\r\n\x05\x64olar\x18\x01 \x01(\x05\x32\xa8\x01\n\x04\x41lta\x12\x43\n\x0eGetTemperature\x12\x16.GetTemperatureRequest\x1a\x17.GetTemperatureResponse\"\x00\x12(\n\x05GetUF\x12\r.GetUFRequest\x1a\x0e.GetUFResponse\"\x00\x12\x31\n\x08GetDolar\x12\x10.GetDolarRequest\x1a\x11.GetDolarResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.alta_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETTEMPERATUREREQUEST._serialized_start=21
  _GETTEMPERATUREREQUEST._serialized_end=58
  _GETTEMPERATURERESPONSE._serialized_start=60
  _GETTEMPERATURERESPONSE._serialized_end=105
  _GETUFREQUEST._serialized_start=107
  _GETUFREQUEST._serialized_end=135
  _GETUFRESPONSE._serialized_start=137
  _GETUFRESPONSE._serialized_end=164
  _GETDOLARREQUEST._serialized_start=166
  _GETDOLARREQUEST._serialized_end=197
  _GETDOLARRESPONSE._serialized_start=199
  _GETDOLARRESPONSE._serialized_end=232
  _ALTA._serialized_start=235
  _ALTA._serialized_end=403
# @@protoc_insertion_point(module_scope)
