# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import alta_pb2 as protos_dot_alta__pb2


class AltaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTemperature = channel.unary_unary(
                '/Alta/GetTemperature',
                request_serializer=protos_dot_alta__pb2.GetTemperatureRequest.SerializeToString,
                response_deserializer=protos_dot_alta__pb2.GetTemperatureResponse.FromString,
                )
        self.GetUF = channel.unary_unary(
                '/Alta/GetUF',
                request_serializer=protos_dot_alta__pb2.GetUFRequest.SerializeToString,
                response_deserializer=protos_dot_alta__pb2.GetUFResponse.FromString,
                )
        self.GetDolar = channel.unary_unary(
                '/Alta/GetDolar',
                request_serializer=protos_dot_alta__pb2.GetDolarRequest.SerializeToString,
                response_deserializer=protos_dot_alta__pb2.GetDolarResponse.FromString,
                )


class AltaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDolar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AltaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTemperature,
                    request_deserializer=protos_dot_alta__pb2.GetTemperatureRequest.FromString,
                    response_serializer=protos_dot_alta__pb2.GetTemperatureResponse.SerializeToString,
            ),
            'GetUF': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUF,
                    request_deserializer=protos_dot_alta__pb2.GetUFRequest.FromString,
                    response_serializer=protos_dot_alta__pb2.GetUFResponse.SerializeToString,
            ),
            'GetDolar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDolar,
                    request_deserializer=protos_dot_alta__pb2.GetDolarRequest.FromString,
                    response_serializer=protos_dot_alta__pb2.GetDolarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Alta', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Alta(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Alta/GetTemperature',
            protos_dot_alta__pb2.GetTemperatureRequest.SerializeToString,
            protos_dot_alta__pb2.GetTemperatureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Alta/GetUF',
            protos_dot_alta__pb2.GetUFRequest.SerializeToString,
            protos_dot_alta__pb2.GetUFResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDolar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Alta/GetDolar',
            protos_dot_alta__pb2.GetDolarRequest.SerializeToString,
            protos_dot_alta__pb2.GetDolarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
